### ISSUE TITLE
There are some parsing errors

### ISSUE THREAD

**Issue by daoye** [interdependence/tree-sitter-htmldjango#2]
`
{% extends 'layout.html' %}
{% block nav %}
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">
                <a href="/">Dashboard</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ request.headers.get('Referer', '/resources/list') }}">Resource management</a>
            </li>
            <li class="breadcrumb-item active">Pick</li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">Attachments</h3>
            </div>
            <form method="POST">
                <input type="hidden"
                       value="{{ request.headers.get('Referer', '/resources/list') }}"
                       name="returnurl" />
                <div class="card-body">
                    <div class="form-group">
                        {% for m in meta.get('attachments', []) %}
                            <div class="form-check my-2">
                                <input class="form-check-input" type="checkbox" name="attachment" value="{{ m.name }}" {{'checked' if m.get('picked', False) }} id="attach_{{ loop.index }}">
                                <label class="form-check-label" for="attach_{{ loop.index }}">{{ m.name }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="spiders">Spider</label>
                        <select name="spider" class="form-control" id="spiders">
                            <option>CGTrader</option>
                        </select>
                    </div>
                    <div class="form-group text-capitalize">
                        <label for="spiders">3D Model formats</label>
                        <div class="form-text text-muted">
                            {% for m in meta.get('formats', []) %}
                            <div class="my-1">
                                Software: {{m.get('software', '')}}
                                Version: {{m.get('version', '')}}
                                Renderer: {{m.get('renderer', '')}}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-start align-items-center">
                    <button type="submit"
                            class="btn btn-primary text-uppercase"
                            id="btn_add_to_download">Append to queue</button>
                    <div class="form-check ml-5">
                        <input class="form-check-input"
                               type="checkbox"
                               name="is_need_image"
                               id="always_download_image"
                               value="true"
                               checked />
                        <label class="form-check-label" for="always_download_image">Always download preview images</label>
                    </div>
                </div>
            </form>
        </div>
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    Basic information <small>- {{ item.get('name', '') }}</small>
                </h3>
                <a class="float-right"
                   href='{{ item.get("source_url", "javascript:;") }}'
                   target="_blank">
                    <i class="fas fa-external-link-alt"></i>
                </a>
            </div>
            <div class="card-body row">
                <div class="col-7 text-center d-flex align-items-center justify-content-center">
                    <img class="img-thumbnail rounded" src='/static/data/images/{{ meta.get("preview") }}' />
                </div>
                <div class="col-5">
                    <div class="form-group row my-0">
                        <label class="col-sm-3 col-form-label font-weight-normal">Publish date</label>
                        <div class="col-sm-3 col-form-label text-muted">{{ item.get('publish_date') }}</div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Model ID</label>
                        <div class="col-sm-3 col-form-label text-muted">{{ item.get('source_id') }}</div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Animated</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('animated') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Rigged</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('rigged') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">VR</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('is_vr') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">AR</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('is_ar') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">PBR</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('is_pbr') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Geometry</label>
                        <div class="col-sm-3 col-form-label text-muted">{{ meta.get('geometry', '') }}</div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Polygons</label>
                        <div class="col-sm-3 col-form-label text-muted">{{ meta.get('polygons', '') }}</div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Vertices</label>
                        <div class="col-sm-3 col-form-label text-muted">{{ meta.get('vertices', '') }}</div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Textures</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('textures') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Materials</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('materials') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">UV Mapping</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('uv_mapping') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Plugins used</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('plugins_used') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                        <label class="col-sm-3 col-form-label font-weight-normal">Unwrapped UVs</label>
                        <div class="col-sm-3 col-form-label text-muted">
                            {% if meta.get('unwarpped_uvs') == 'true' %}
                                <i class="fas fa-check-circle text-success"></i>
                            {% else %}
                                <i class="far fa-times-circle text-danger"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-12">{{ item.get('memo', '') }}</div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}<script src="/static/pages/resources/prepare.js"></script>{% endblock %}
`

Hi,hero.  see this code, It looks like the syntax is not parsed correctly, but I don't know what the cause of the problem is

**Comment by interdependence** [comment]
It fails on the line:

```htmldjango
<a href="{{ request.headers.get('Referer', '/resources/list') }}">Resource management</a>
```
As far as I am aware, Django does not allow for passing arguments to callables in templates.

Does your code work regardless of syntax parsing errors?

**Comment by daoye** [comment]
ok. 
I'm use jinja.html with flask.
Doesn't this grammar support Jinja?

**Comment by interdependence** [comment]
This grammar is only designed to parse the [Django template language](https://docs.djangoproject.com/en/4.2/ref/templates/language).
