### ISSUE TITLE
Template tag starting with builtin tag or function highlighted incorrectly

### ISSUE THREAD

**Issue by krims0n32** [interdependence/tree-sitter-htmldjango#3]
![image](https://github.com/interdependence/tree-sitter-htmldjango/assets/661853/24e01f5d-3a36-48ff-8082-94721757945f)

As you can see the parses sees a custom template tag form_input as a function (for) and highlights only that part. Also happens with other "reserved" keywords. Happy to provide any more info if needed. Thanks!

**Comment by interdependence** [comment]
Good catch! I will take a look and see if there is an obvious solution.

**Comment by interdependence** [comment]
Should be fixed in 8873e3d.

**Comment by krims0n32** [comment]
Fixed, thanks!
